<a href="https://colab.research.google.com/github/emilytadelmauro/adult-census/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import pandas as pd

# Ruta del archivo (usa raw string `r""` para evitar problemas con las barras invertidas)
file_path = "https://raw.githubusercontent.com/emilytadelmauro/adult-census/76e857d0a6a4a00cd8f2b10215d5c2b98b4d5875/adult.csv"

In [67]:
# Cargar el dataset en un DataFrame
df = pd.read_csv(file_path)

# Mostrar las primeras filas
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [68]:
# prompt: create a new column called income2 with randon numbers from 20000 to 100000 use de column income as guide. If income "<=50k" generate a randon number <50000 if income is ">50k" generate a randon number >50000 and <100000


# Crear la columna 'income2'
df['income2'] = np.where(df['income'] == '<=50K',
                         np.random.randint(20000, 50000, size=len(df)),
                         np.random.randint(50000, 100000, size=len(df)))

# Mostrar las primeras filas para verificar
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,income2
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,45255
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K,31691
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K,39661
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K,24499
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K,24370

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
 15  income2         32561 non-null  int64
dtypes: int64(7), object(9)
memory usage: 4.0+ MB

In [70]:
df["marital.status"].describe()
df["marital.status"].value_counts()
df["marital.status"].value_counts(normalize=True)

marital.status
Married-civ-spouse       0.459937
Never-married            0.328092
Divorced                 0.136452
Separated                0.031479
Widowed                  0.030497
Married-spouse-absent    0.012837
Married-AF-spouse        0.000706
Name: proportion, dtype: float64

In [71]:
df["marital.status"].dtype
df["marital.status"]=df["marital.status"].astype("category")
# also can be done using pd.Series but is less effiecient than astype("category")
#series1 = pd.Series("marital.status")
#series2 = pd.Series("marital.status",dtype="category")
df["marital.status"].dtype

CategoricalDtype(categories=['Divorced', 'Married-AF-spouse', 'Married-civ-spouse',
                  'Married-spouse-absent', 'Never-married', 'Separated',
                  'Widowed'],
, ordered=False, categories_dtype=object)

In [72]:
#Tranforming marital status in a categorical variable
df["marital.status"]=df["marital.status"].astype("category")
 # if we have a defined order for out category
#df=pd.Categorical(df, categories=["Never-married","Married-AF-spouse",
                                 #  "Married-civ-spouse","Married-spouse-absent",
                                 #  "Divorced","Widowed"],ordered=True)

In [73]:
#Setting data types into a dictionary
df_dtypes={"age":int,"workclass":"category","fnlwgt":int,"education":"category",
           "education.num":int,"marital.status":"category","occupation":"category",
           "relationship":"category","race":"category","sex":"category","native.country":"category",
           "income":"category"}
#Applying dictionary
df=df.astype(df_dtypes)
# charge the dataframe using the dictionary above to specify the data types
#df2 = pd.read_csv(
#  "df.csv",
#  dtype=df_dtypes)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  category
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  category
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  category
 6   occupation      32561 non-null  category
 7   relationship    32561 non-null  category
 8   race            32561 non-null  category
 9   sex             32561 non-null  category
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  category
 14  income          32561 non-null  category
 15  income2         32561 non-null  int64
dtypes: category(9), int64(7)
memory usage: 2.0 MB

In [82]:
#groupby_object=df.groupby(by=["income2"])["age", "education.num"].sum()
groupby_object = df.groupby(by=["income2"])[["age", "education.num"]].sum()

groupby_object

         age  education.num
income2
20000     66             20
20002     86             18
20003     23             10
20004     43              2
20007     26              8
...      ...            ...
99976     45              8
99980     70             13
99981     40             16
99985     56             13
99988     46             10

[24087 rows x 2 columns]

In [89]:
groupby_object = df.groupby(by=["income2"])[["age", "education.num"]].mean()
groupby_object

          age  education.num
income2
20000    33.0           10.0
20002    43.0            9.0
20003    23.0           10.0
20004    43.0            2.0
20007    26.0            8.0
...       ...            ...
99976    45.0            8.0
99980    70.0           13.0
99981    40.0           16.0
99985    56.0           13.0
99988    46.0           10.0

[24087 rows x 2 columns]

In [90]:
#groupby_object=df.groupby(by=["income2"])["age", "education.num"].sum()
groupby_object = df.groupby(by=["income2"])[["age", "education.num"]].sum()

groupby_object

         age  education.num
income2
20000     66             20
20002     86             18
20003     23             10
20004     43              2
20007     26              8
...      ...            ...
99976     45              8
99980     70             13
99981     40             16
99985     56             13
99988     46             10

[24087 rows x 2 columns]

In [93]:
# Group the adult dataset by "Sex" and "Above/Below 50k"
gb = df.groupby(by=["sex", "income"])
print(gb.size())
print(gb.mean())

sex     income
Female  <=50K      9592
        >50K       1179
Male    <=50K     15128
        >50K       6662
dtype: int64

<ipython-input-93-32efe6d9cd7c>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  gb = df.groupby(by=["sex", "income"])

TypeError: category dtype does not support aggregation 'mean'